apiVersion: template.openshift.io/v1
kind: Template
message: Aplicacion java
metadata:
  annotations:
    description: Template para creación de aplicaciones java
    openshift.io/display-name: OpenJDK
  labels:
    template: java-dev
  name: java-dev
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: The application's http port.
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8443-tcp
          port: 8443
          protocol: TCP
          targetPort: 8443
        - name: 8778-tcp
          port: 8778
          protocol: TCP
          targetPort: 8778
      selector:
        deploymentConfig: ${APPLICATION_NAME}
      type: ClusterIP
  - apiVersion: v1
    id: ${APPLICATION_NAME}-http
    kind: Route
    metadata:
      annotations:
        description: Route for application's http service.
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: ${APPLICATION_NAME}
        weight: 100
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      source:
        type: Binary
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: java:8
            namespace: openshift
        type: Source
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: ${{REPLICAS}}
      triggers: []
      selector:
        deploymentConfig: ${APPLICATION_NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            deploymentConfig: ${APPLICATION_NAME}
          name: ${APPLICATION_NAME}
        spec:
          containers:
            - env:
                - name: SPRING_PROFILES_ACTIVE
                  value: openshift
                - name: TZ
                  value: America/Bogota
              image: ${APPLICATION_NAME}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
                - containerPort: 8778
                  protocol: TCP
              livenessProbe:
                failureThreshold: 8
                httpGet:
                  path: /actuator/health
                  port: ${{ACTUATOR_PORT}}
                  scheme: HTTP
                initialDelaySeconds: 100
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 8
                httpGet:
                  path: /actuator/health
                  port: ${{ACTUATOR_PORT}}
                  scheme: HTTP
                initialDelaySeconds: 40
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 400m
                  memory: 500Mi
                requests:
                  cpu: 50m
                  memory: 300Mi
              volumeMounts:
                - mountPath: /deployments/config/mappings.json
                  name: ${APPLICATION_NAME}-mappings
                  subPath: mappings.json
          volumes:
            - configMap:
                defaultMode: 420
                name: ${APPLICATION_NAME}-mappings
              name: ${APPLICATION_NAME}-mappings
parameters:
  - description: The name for the application.
    displayName: Nombre de la aplicación
    name: APPLICATION_NAME
    required: true
    value: openjdk-app
  - description: Número de réplicas
    displayName: Número de réplicas
    name: REPLICAS
    required: true
    value: '1'
  - description: Puerto del actuador de spring usado para los health checks
    displayName: Puerto del actuador de spring usado para los health checks
    name: ACTUATOR_PORT
    required: true
    value: '8080'
